apiVersion: v1
kind: ConfigMap
metadata:
  name: user-admin-cm
data:
  index.html: |-
    <!DOCTYPE html>
    <html>
    <head>
    <title>master</title>
    </head>
    <body>

    <h1>master</h1>

    </body>
    </html>